# Generated by Django 3.2a1 on 2021-01-20 23:45

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=192)),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='portifolio')),
                ('conteudo', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='portifolio')),
                ('descricao', ckeditor.fields.RichTextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
